In [2]:
import pandas as pd

In [ ]:
df = pd.read_csv('../lsy/2023 강남구 따릉이 이용정보/2301_강남구_따릉이_이용정보.csv')
df

,대여일시,대여 대여소번호,대여거치대,반납일시,반납대여소번호,반납대여소명,반납거치대,이용시간(분),이용거리(M),생년,성별,이용자종류
0,2023-01-01 00:11:12,2427,0,2023-01-01 00:18:25,2416.0,한티역 6번 출구,0,7,1196.26,1978.0,M,내국인
1,2023-01-01 00:14:25,2309,0,2023-01-01 00:18:43,2313.0,금원빌딩 앞,0,4,934.81,1963.0,NaN,내국인
2,2023-01-01 00:12:04,2431,0,2023-01-01 00:21:16,2404.0,대모산입구역 4번 출구 앞,0,9,1299.99,1989.0,NaN,내국인
3,2023-01-01 00:15:24,2333,0,2023-01-01 00:22:07,2327.0,뱅뱅사거리 랜드마크타워 앞,0,6,617.48,1960.0,NaN,내국인
4,2023-01-01 00:18:23,2423,0,2023-01-01 00:25:50,3651.0,개포동역 4번출구,0,7,1380.00,1995.0,NaN,내국인
...,...,...,...,...,...,...,...,...,...,...,...,...
34932,2023-01-31 23:49:48,4914,0,2023-02-01 00:13:19,2339.0,현대아파트 정문 앞,0,23,5270.93,1981.0,M,내국인
34933,2023-01-31 23:59:07,2342,0,2023-02-01 00:15:14,2324.0,천주교 대치 2동 교회 옆,0,16,1900.82,2004.0,M,내국인
34934,2023-01-31 23:33:46,2369,0,2023-02-01 00:28:07,2357.0,르네상스호텔사거리 역삼지하보도 3번출구 앞 (더 오번 빌딩 명동칼국수 앞),0,54,1890.91,1995.0,M,내국인
34935,2023-01-31 23:35:54,2304,0,2023-02-01 01:00:53,2371.0,한국우편사업진흥원,0,84,12660.00,2002.0,F,내국인
34936,2023-01-31 22:53:00,2306,0,2023-02-01 05:16:22,2301.0,현대고등학교 건너편,0,383,698.93,1953.0,M,내국인

In [11]:
df.대여일시 = pd.to_datetime(df.대여일시)

In [12]:
df[(df.대여일시.dt.hour == 17) | (df.대여일시.dt.hour == 18) | (df.대여일시.dt.hour == 19)].sort_values(ascending=True, by='대여일시')

,대여일시,대여 대여소번호,대여거치대,반납일시,반납대여소번호,반납대여소명,반납거치대,이용시간(분),이용거리(M),생년,성별,이용자종류
496,2023-01-01 17:01:09,2341,99,2023-01-01 17:32:18,2341.0,일원역 4~5번 출구 사이,99,31,4710.00,1980.0,F,내국인
477,2023-01-01 17:01:45,2369,0,2023-01-01 17:08:57,2382.0,역삼동 sk뷰 501동앞,0,7,650.00,1978.0,NaN,내국인
473,2023-01-01 17:01:51,4917,0,2023-01-01 17:08:03,2342.0,대청역 1번출구 뒤,0,6,788.01,1996.0,M,내국인
495,2023-01-01 17:02:33,3614,0,2023-01-01 17:32:16,2340.0,삼호물산버스정류장(23370) 옆,0,29,4020.00,1983.0,NaN,내국인
564,2023-01-01 17:02:53,4908,0,2023-01-01 18:47:22,2429.0,압구정로데오역 6번출구,0,104,3580.00,1979.0,NaN,내국인
...,...,...,...,...,...,...,...,...,...,...,...,...
34667,2023-01-31 19:57:59,2331,0,2023-01-31 20:11:50,2421.0,신논현역 4번출구,0,13,2505.17,2002.0,NaN,내국인
34658,2023-01-31 19:58:00,2412,0,2023-01-31 20:03:16,3641.0,대청역,0,5,876.03,1999.0,NaN,내국인
34678,2023-01-31 19:58:04,2349,0,2023-01-31 20:18:10,2303.0,논현역 10번출구,0,20,1863.50,1988.0,NaN,내국인
34656,2023-01-31 19:58:26,2319,0,2023-01-31 20:01:53,4906.0,섬유센터 앞,0,3,500.00,1978.0,M,내국인
34666,2023-01-31 19:58:44,2377,0,2023-01-31 20:11:22,2411.0,세곡동 성당,0,12,2191.52,1993.0,M,내국인

In [14]:
dfs = []

for num in ['01', '02', '03', '04', '05', '06', '07', '08', '09', '10', '11', '12']:
    df = pd.read_csv(f'../lsy/2023 강남구 따릉이 이용정보/23{num}_강남구_따릉이_이용정보.csv')
    df.대여일시 = pd.to_datetime(df.대여일시)
    dfs.append(df[(df.대여일시.dt.hour == 17) | (df.대여일시.dt.hour == 18) | (df.대여일시.dt.hour == 19)].sort_values(ascending=True, by='대여일시').반납대여소번호)

In [15]:
dfs = [i.astype(int) for i in dfs]

In [19]:
dfs[0].values

array([2341, 2382, 2342, ..., 2303, 4906, 2411], shape=(8154,))

In [22]:
df1_2023 = dfs[0]
df2_2023 = dfs[1]
df3_2023 = dfs[2]
df4_2023 = dfs[3]
df5_2023 = dfs[4]
df6_2023 = dfs[5]
df7_2023 = dfs[6]
df8_2023 = dfs[7]
df9_2023 = dfs[8]
df10_2023 = dfs[9]
df11_2023 = dfs[10]
df12_2023 = dfs[11]

In [ ]:
# df1_2023.to_csv('../lsy/2023 강남구 따릉이 이용정보/2301_강남구_따릉이_이용정보.csv')
# df2_2023.to_csv('../Data/ddri/ddri_work/3조 공유폴더/2023 강남구 따릉이 이용정보/df2_2023.csv')
# df3_2023.to_csv('../Data/ddri/ddri_work/3조 공유폴더/2023 강남구 따릉이 이용정보/df3_2023.csv')
# df4_2023.to_csv('../Data/ddri/ddri_work/3조 공유폴더/2023 강남구 따릉이 이용정보/df4_2023.csv')
# df5_2023.to_csv('../Data/ddri/ddri_work/3조 공유폴더/2023 강남구 따릉이 이용정보/df5_2023.csv')
# df6_2023.to_csv('../Data/ddri/ddri_work/3조 공유폴더/2023 강남구 따릉이 이용정보/df6_2023.csv')
# df7_2023.to_csv('../Data/ddri/ddri_work/3조 공유폴더/2023 강남구 따릉이 이용정보/df7_2023.csv')
# df8_2023.to_csv('../Data/ddri/ddri_work/3조 공유폴더/2023 강남구 따릉이 이용정보/df8_2023.csv')
# df9_2023.to_csv('../Data/ddri/ddri_work/3조 공유폴더/2023 강남구 따릉이 이용정보/df9_2023.csv')
# df10_2023.to_csv('../Data/ddri/ddri_work/3조 공유폴더/2023 강남구 따릉이 이용정보/df10_2023.csv')
# df11_2023.to_csv('../Data/ddri/ddri_work/3조 공유폴더/2023 강남구 따릉이 이용정보/df11_2023.csv')
# df12_2023.to_csv('../Data/ddri/ddri_work/3조 공유폴더/2023 강남구 따릉이 이용정보/df12_2023.csv')

OSError: Cannot save file into a non-existent directory: '../Data/ddri/ddri_work/3조 공유폴더/2023 강남구 따릉이 이용정보'

In [24]:
df1_2023

496      2341
477      2382
473      2342
495      2340
564      2429
         ...
34667    2421
34658    3641
34678    2303
34656    4906
34666    2411
Name: 반납대여소번호, Length: 8154, dtype: int64

In [2]:
import pandas as pd

In [ ]:
df = pd.read_csv('../lsy/2023 강남구 따릉이 이용정보/2301_강남구_따릉이_이용정보.csv')

In [4]:
df

,대여일시,대여 대여소번호,대여거치대,반납일시,반납대여소번호,반납대여소명,반납거치대,이용시간(분),이용거리(M),생년,성별,이용자종류
0,2023-01-01 00:11:12,2427,0,2023-01-01 00:18:25,2416.0,한티역 6번 출구,0,7,1196.26,1978.0,M,내국인
1,2023-01-01 00:14:25,2309,0,2023-01-01 00:18:43,2313.0,금원빌딩 앞,0,4,934.81,1963.0,NaN,내국인
2,2023-01-01 00:12:04,2431,0,2023-01-01 00:21:16,2404.0,대모산입구역 4번 출구 앞,0,9,1299.99,1989.0,NaN,내국인
3,2023-01-01 00:15:24,2333,0,2023-01-01 00:22:07,2327.0,뱅뱅사거리 랜드마크타워 앞,0,6,617.48,1960.0,NaN,내국인
4,2023-01-01 00:18:23,2423,0,2023-01-01 00:25:50,3651.0,개포동역 4번출구,0,7,1380.00,1995.0,NaN,내국인
...,...,...,...,...,...,...,...,...,...,...,...,...
34932,2023-01-31 23:49:48,4914,0,2023-02-01 00:13:19,2339.0,현대아파트 정문 앞,0,23,5270.93,1981.0,M,내국인
34933,2023-01-31 23:59:07,2342,0,2023-02-01 00:15:14,2324.0,천주교 대치 2동 교회 옆,0,16,1900.82,2004.0,M,내국인
34934,2023-01-31 23:33:46,2369,0,2023-02-01 00:28:07,2357.0,르네상스호텔사거리 역삼지하보도 3번출구 앞 (더 오번 빌딩 명동칼국수 앞),0,54,1890.91,1995.0,M,내국인
34935,2023-01-31 23:35:54,2304,0,2023-02-01 01:00:53,2371.0,한국우편사업진흥원,0,84,12660.00,2002.0,F,내국인
34936,2023-01-31 22:53:00,2306,0,2023-02-01 05:16:22,2301.0,현대고등학교 건너편,0,383,698.93,1953.0,M,내국인

In [16]:
df.반납일시 = [반납일시.split()[0] for 반납일시 in df.반납일시]
df

,대여일시,대여 대여소번호,대여거치대,반납일시,반납대여소번호,반납대여소명,반납거치대,이용시간(분),이용거리(M),생년,성별,이용자종류
0,2023-01-01 00:11:12,2427,0,2023-01-01,2416.0,한티역 6번 출구,0,7,1196.26,1978.0,M,내국인
1,2023-01-01 00:14:25,2309,0,2023-01-01,2313.0,금원빌딩 앞,0,4,934.81,1963.0,NaN,내국인
2,2023-01-01 00:12:04,2431,0,2023-01-01,2404.0,대모산입구역 4번 출구 앞,0,9,1299.99,1989.0,NaN,내국인
3,2023-01-01 00:15:24,2333,0,2023-01-01,2327.0,뱅뱅사거리 랜드마크타워 앞,0,6,617.48,1960.0,NaN,내국인
4,2023-01-01 00:18:23,2423,0,2023-01-01,3651.0,개포동역 4번출구,0,7,1380.00,1995.0,NaN,내국인
...,...,...,...,...,...,...,...,...,...,...,...,...
34932,2023-01-31 23:49:48,4914,0,2023-02-01,2339.0,현대아파트 정문 앞,0,23,5270.93,1981.0,M,내국인
34933,2023-01-31 23:59:07,2342,0,2023-02-01,2324.0,천주교 대치 2동 교회 옆,0,16,1900.82,2004.0,M,내국인
34934,2023-01-31 23:33:46,2369,0,2023-02-01,2357.0,르네상스호텔사거리 역삼지하보도 3번출구 앞 (더 오번 빌딩 명동칼국수 앞),0,54,1890.91,1995.0,M,내국인
34935,2023-01-31 23:35:54,2304,0,2023-02-01,2371.0,한국우편사업진흥원,0,84,12660.00,2002.0,F,내국인
34936,2023-01-31 22:53:00,2306,0,2023-02-01,2301.0,현대고등학교 건너편,0,383,698.93,1953.0,M,내국인

In [14]:
df.groupby(['반납일시']).size()

반납일시
2023-01-01     719
2023-01-02    1186
2023-01-03    1300
2023-01-04    1536
2023-01-05    1456
2023-01-06    1458
2023-01-07     860
2023-01-08     910
2023-01-09    1686
2023-01-10    1813
2023-01-11    1810
2023-01-12    1999
2023-01-13     479
2023-01-14     512
2023-01-15     451
2023-01-16    1591
2023-01-17    1608
2023-01-18    1602
2023-01-19    1578
2023-01-20    1086
2023-01-21     618
2023-01-22     508
2023-01-23     570
2023-01-24     354
2023-01-25     907
2023-01-26     566
2023-01-27     949
2023-01-28     777
2023-01-29     798
2023-01-30    1438
2023-01-31    1805
2023-02-01       7
dtype: int64

In [ ]:
df = pd.read_csv('../lsy/2023 강남구 따릉이 이용정보/2301_강남구_따릉이_이용정보.csv')

In [18]:
ddri_count_1to6 = []
for num in ['01', '02', '03', '04', '05', '06']:
    df = pd.read_csv(f'../lsy/2023 강남구 따릉이 이용정보/23{num}_강남구_따릉이_이용정보.csv')
    df.반납일시 = [반납일시.split()[0] for 반납일시 in df.반납일시]
    ddri_count_1to6.append(df.groupby(['반납일시']).size())

In [19]:
ddri_count_1to6[0]

반납일시
2023-01-01     719
2023-01-02    1186
2023-01-03    1300
2023-01-04    1536
2023-01-05    1456
2023-01-06    1458
2023-01-07     860
2023-01-08     910
2023-01-09    1686
2023-01-10    1813
2023-01-11    1810
2023-01-12    1999
2023-01-13     479
2023-01-14     512
2023-01-15     451
2023-01-16    1591
2023-01-17    1608
2023-01-18    1602
2023-01-19    1578
2023-01-20    1086
2023-01-21     618
2023-01-22     508
2023-01-23     570
2023-01-24     354
2023-01-25     907
2023-01-26     566
2023-01-27     949
2023-01-28     777
2023-01-29     798
2023-01-30    1438
2023-01-31    1805
2023-02-01       7
dtype: int64

In [20]:
ddri_count_1to6[1]

반납일시
2023-02-01    1658
2023-02-02    1640
2023-02-03    1628
2023-02-04    1248
2023-02-05    1086
2023-02-06    1857
2023-02-07    1926
2023-02-08    1930
2023-02-09    2027
2023-02-10    1469
2023-02-11    1475
2023-02-12    1257
2023-02-13    2090
2023-02-14    2044
2023-02-15    2114
2023-02-16    2021
2023-02-17    2171
2023-02-18    1503
2023-02-19    1122
2023-02-20    1710
2023-02-21    1886
2023-02-22    2100
2023-02-23    2126
2023-02-24    1994
2023-02-25    1432
2023-02-26    1407
2023-02-27    2200
2023-02-28    2238
2023-03-01      13
dtype: int64

In [21]:
df = pd.read_csv('../lsy/2023 강남구 따릉이 이용정보/2301_강남구_따릉이_이용정보.csv')
df

,대여일시,대여 대여소번호,대여거치대,반납일시,반납대여소번호,반납대여소명,반납거치대,이용시간(분),이용거리(M),생년,성별,이용자종류
0,2023-01-01 00:11:12,2427,0,2023-01-01 00:18:25,2416.0,한티역 6번 출구,0,7,1196.26,1978.0,M,내국인
1,2023-01-01 00:14:25,2309,0,2023-01-01 00:18:43,2313.0,금원빌딩 앞,0,4,934.81,1963.0,NaN,내국인
2,2023-01-01 00:12:04,2431,0,2023-01-01 00:21:16,2404.0,대모산입구역 4번 출구 앞,0,9,1299.99,1989.0,NaN,내국인
3,2023-01-01 00:15:24,2333,0,2023-01-01 00:22:07,2327.0,뱅뱅사거리 랜드마크타워 앞,0,6,617.48,1960.0,NaN,내국인
4,2023-01-01 00:18:23,2423,0,2023-01-01 00:25:50,3651.0,개포동역 4번출구,0,7,1380.00,1995.0,NaN,내국인
...,...,...,...,...,...,...,...,...,...,...,...,...
34932,2023-01-31 23:49:48,4914,0,2023-02-01 00:13:19,2339.0,현대아파트 정문 앞,0,23,5270.93,1981.0,M,내국인
34933,2023-01-31 23:59:07,2342,0,2023-02-01 00:15:14,2324.0,천주교 대치 2동 교회 옆,0,16,1900.82,2004.0,M,내국인
34934,2023-01-31 23:33:46,2369,0,2023-02-01 00:28:07,2357.0,르네상스호텔사거리 역삼지하보도 3번출구 앞 (더 오번 빌딩 명동칼국수 앞),0,54,1890.91,1995.0,M,내국인
34935,2023-01-31 23:35:54,2304,0,2023-02-01 01:00:53,2371.0,한국우편사업진흥원,0,84,12660.00,2002.0,F,내국인
34936,2023-01-31 22:53:00,2306,0,2023-02-01 05:16:22,2301.0,현대고등학교 건너편,0,383,698.93,1953.0,M,내국인

In [28]:
df.대여일시 = pd.to_datetime(df.대여일시)

In [29]:
df.대여일시.dt.hour

0         0
1         0
2         0
3         0
4         0
         ..
34932    23
34933    23
34934    23
34935    23
34936    22
Name: 대여일시, Length: 34937, dtype: int32

In [30]:
import pandas as pd

In [34]:
ddri = pd.read_csv('../lsy/ddri_prediction_long_train_2023_2024.csv')
ddri

,station_id,station_name,station_group,date,hour,rental_count,cluster,mapped_dong_code,weekday,month,holiday,temperature,humidity,precipitation,wind_speed
0,2312,청담역 13번 출구 앞,주거 도착형,2023-01-01,0,0,2,11680565,6,1,1,-2.0,81,0.0,9.3
1,2312,청담역 13번 출구 앞,주거 도착형,2023-01-01,1,0,2,11680565,6,1,1,-1.7,82,0.0,9.3
2,2312,청담역 13번 출구 앞,주거 도착형,2023-01-01,2,0,2,11680565,6,1,1,-0.8,77,0.0,10.8
3,2312,청담역 13번 출구 앞,주거 도착형,2023-01-01,3,0,2,11680565,6,1,1,-1.8,83,0.0,8.0
4,2312,청담역 13번 출구 앞,주거 도착형,2023-01-01,4,0,2,11680565,6,1,1,-4.0,90,0.0,8.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263155,4917,일원에코파크 주차장,주거 도착형,2024-12-31,19,1,2,11680730,1,12,0,-2.0,65,0.0,6.4
263156,4917,일원에코파크 주차장,주거 도착형,2024-12-31,20,1,2,11680730,1,12,0,-2.5,69,0.0,4.9
263157,4917,일원에코파크 주차장,주거 도착형,2024-12-31,21,1,2,11680730,1,12,0,-2.9,70,0.0,4.5
263158,4917,일원에코파크 주차장,주거 도착형,2024-12-31,22,0,2,11680730,1,12,0,-2.9,70,0.0,3.2
263159,4917,일원에코파크 주차장,주거 도착형,2024-12-31,23,0,2,11680730,1,12,0,-3.2,71,0.0,2.7

station_id - 대여소 id   
station_name - 대여소 이름   
station_group - 군집 라벨    
rental_count -    
cluster -    
weekday -

In [36]:
ddri.head(30)

,station_id,station_name,station_group,date,hour,rental_count,cluster,mapped_dong_code,weekday,month,holiday,temperature,humidity,precipitation,wind_speed
0,2312,청담역 13번 출구 앞,주거 도착형,2023-01-01,0,0,2,11680565,6,1,1,-2.0,81,0.0,9.3
1,2312,청담역 13번 출구 앞,주거 도착형,2023-01-01,1,0,2,11680565,6,1,1,-1.7,82,0.0,9.3
2,2312,청담역 13번 출구 앞,주거 도착형,2023-01-01,2,0,2,11680565,6,1,1,-0.8,77,0.0,10.8
3,2312,청담역 13번 출구 앞,주거 도착형,2023-01-01,3,0,2,11680565,6,1,1,-1.8,83,0.0,8.0
4,2312,청담역 13번 출구 앞,주거 도착형,2023-01-01,4,0,2,11680565,6,1,1,-4.0,90,0.0,8.6
5,2312,청담역 13번 출구 앞,주거 도착형,2023-01-01,5,0,2,11680565,6,1,1,-4.2,89,0.0,6.8
6,2312,청담역 13번 출구 앞,주거 도착형,2023-01-01,6,0,2,11680565,6,1,1,-4.2,88,0.0,5.6
7,2312,청담역 13번 출구 앞,주거 도착형,2023-01-01,7,0,2,11680565,6,1,1,-5.1,88,0.0,5.5
8,2312,청담역 13번 출구 앞,주거 도착형,2023-01-01,8,0,2,11680565,6,1,1,-5.4,88,0.0,6.9
9,2312,청담역 13번 출구 앞,주거 도착형,2023-01-01,9,0,2,11680565,6,1,1,-4.4,80,0.0,7.7
10,2312,청담역 13번 출구 앞,주거 도착형,2023-01-01,10,0,2,11680565,6,1,1,-2.2,67,0.0,7.6
11,2312,청담역 13번 출구 앞,주거 도착형,2023-01-01,11,0,2,11680565,6,1,1,-0.6,56,0.0,10.3
12,2312,청담역 13번 출구 앞,주거 도착형,2023-01-01,12,1,2,11680565,6,1,1,0.8,42,0.0,13.2
13,2312,청담역 13번 출구 앞,주거 도착형,2023-01-01,13,0,2,11680565,6,1,1,1.5,32,0.0,16.6
14,2312,청담역 13번 출구 앞,주거 도착형,2023-01-01,14,1,2,11680565,6,1,1,1.8,29,0.0,17.6
15,2312,청담역 13번 출구 앞,주거 도착형,2023-01-01,15,0,2,11680565,6,1,1,1.5,26,0.0,19.0
16,2312,청담역 13번 출구 앞,주거 도착형,2023-01-01,16,0,2,11680565,6,1,1,0.3,30,0.0,17.3
17,2312,청담역 13번 출구 앞,주거 도착형,2023-01-01,17,0,2,11680565,6,1,1,-1.5,38,0.0,12.9
18,2312,청담역 13번 출구 앞,주거 도착형,2023-01-01,18,0,2,11680565,6,1,1,-3.5,44,0.0,10.0
19,2312,청담역 13번 출구 앞,주거 도착형,2023-01-01,19,0,2,11680565,6,1,1,-4.4,47,0.0,11.9
20,2312,청담역 13번 출구 앞,주거 도착형,2023-01-01,20,0,2,11680565,6,1,1,-5.1,48,0.0,13.5
21,2312,청담역 13번 출구 앞,주거 도착형,2023-01-01,21,1,2,11680565,6,1,1,-4.9,53,0.0,14.2
22,2312,청담역 13번 출구 앞,주거 도착형,2023-01-01,22,0,2,11680565,6,1,1,-5.1,53,0.0,14.3
23,2312,청담역 13번 출구 앞,주거 도착형,2023-01-01,23,0,2,11680565,6,1,1,-5.9,55,0.0,12.1
24,2312,청담역 13번 출구 앞,주거 도착형,2023-01-02,0,0,2,11680565,0,1,0,-6.2,54,0.0,10.6
25,2312,청담역 13번 출구 앞,주거 도착형,2023-01-02,1,0,2,11680565,0,1,0,-6.4,53,0.0,9.9
26,2312,청담역 13번 출구 앞,주거 도착형,2023-01-02,2,0,2,11680565,0,1,0,-6.7,53,0.0,10.1
27,2312,청담역 13번 출구 앞,주거 도착형,2023-01-02,3,0,2,11680565,0,1,0,-7.1,53,0.0,10.5
28,2312,청담역 13번 출구 앞,주거 도착형,2023-01-02,4,0,2,11680565,0,1,0,-7.6,53,0.0,10.1
29,2312,청담역 13번 출구 앞,주거 도착형,2023-01-02,5,0,2,11680565,0,1,0,-8.1,54,0.0,10.0

In [37]:
from sklearn.model_selection import train_test_split

In [38]:
ddri.rental_count.unique()

array([ 0,  1,  2,  3,  5,  4,  6,  7,  8, 10,  9, 11, 12, 13, 14, 15, 16,
       17, 21, 19, 29, 26, 20, 24, 18, 22, 33, 32, 28, 23, 25, 27, 31, 36])

In [49]:
ddri.columns
columns = ['hour', 'cluster', 
           'mapped_dong_code', 'weekday', 'month', 'holiday', 'temperature', 'humidity', 
           'precipitation', 'wind_speed']

In [52]:
ddri_morning = ddri[ddri.station_group == '아침 도착 업무 집중형']
ddri_morning[columns]

,hour,cluster,mapped_dong_code,weekday,month,holiday,temperature,humidity,precipitation,wind_speed
52632,0,1,11680610,6,1,1,-2.0,81,0.0,9.3
52633,1,1,11680610,6,1,1,-1.7,82,0.0,9.3
52634,2,1,11680610,6,1,1,-0.8,77,0.0,10.8
52635,3,1,11680610,6,1,1,-1.8,83,0.0,8.0
52636,4,1,11680610,6,1,1,-4.0,90,0.0,8.6
...,...,...,...,...,...,...,...,...,...,...
157891,19,1,11680750,1,12,0,-2.0,65,0.0,6.4
157892,20,1,11680750,1,12,0,-2.5,69,0.0,4.9
157893,21,1,11680750,1,12,0,-2.9,70,0.0,4.5
157894,22,1,11680750,1,12,0,-2.9,70,0.0,3.2
157895,23,1,11680750,1,12,0,-3.2,71,0.0,2.7

In [53]:
feature = ddri_morning[columns]
target = ddri_morning.rental_count

In [56]:
train_data, test_data, train_target, test_target = train_test_split(
    feature, target, random_state=42
)

In [57]:
from sklearn.ensemble import RandomForestRegressor

In [58]:
rf = RandomForestRegressor()

In [59]:
rf.fit(train_data, train_target)

RandomForestRegressor()

In [60]:
rf.score(train_data, train_target)

0.9476523603734809

In [61]:
rf.score(test_data, test_target)

0.6406310602745742

In [65]:
from lightgbm import LGBMRegressor

In [66]:
lgb = LGBMRegressor(max_depth=-1)
lgb.fit(train_data, train_target)
print(lgb.score(train_data, train_target), lgb.score(test_data, test_target))

[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.002093 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 744
[LightGBM] [Info] Number of data points in the train set: 39474, number of used features: 9
[LightGBM] [Info] Start training from score 1.432791
0.7069775652740372 0.6580927818522475

In [67]:
from xgboost import XGBRegressor

In [69]:
xgb = XGBRegressor()
xgb.fit(train_data, train_target)
print(xgb.score(train_data, train_target), xgb.score(test_data, test_target))

0.7474911212921143 0.645359992980957

In [72]:
from sklearn.ensemble import StackingRegressor

In [73]:
from sklearn.linear_model import LinearRegression

In [91]:
estimators = [
    ('rf', RandomForestRegressor(
    n_estimators=300,
    max_depth=15,
    min_samples_split=5,
    min_samples_leaf=2,
    random_state=42,
    n_jobs=-1)),
    ('lgb', LGBMRegressor(n_estimators=500,
    learning_rate=0.05,
    max_depth=-1,
    num_leaves=31,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42)),
    ('xgb', XGBRegressor(
    n_estimators=500,
    learning_rate=0.05,
    max_depth=6,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42))
]

# 2차 모델
final_estimator = LinearRegression()

stack_model = StackingRegressor(
    estimators=estimators,
    final_estimator=final_estimator,
    cv=5,
    n_jobs=-1
)

stack_model.fit(train_data, train_target)

print(stack_model.score(train_data, train_target), stack_model.score(test_data, test_target))

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001275 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 744
[LightGBM] [Info] Number of data points in the train set: 39474, number of used features: 9
[LightGBM] [Info] Start training from score 1.432791
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002776 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002491 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 739
[LightGBM] [Info] Total Bins 737
[LightGBM] [Info] Number of data points in the train set: 31579, number of used features: 9
[LightGBM] [Info] Number of data points in the train set: 31579, number of used features: 9
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.003092 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.003084 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 737
[LightGBM] [Info] Total Bins 737
[LightGBM] [Info] Number of data points in the train set: 31579, number of used features: 9
[LightGBM] [Info] Number of data points in the train set: 31579, number of used features: 9
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002503 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 735
[LightGBM] [Info] Start training from score 1.432059[LightGBM] [Info] Number of data points in the train set: 31580, number of used features: 9

[LightGBM] [Info] Start training from score 1.439153
[LightGBM] [Info] Start training from score 1.436303
[LightGBM] [Info] Start training from score 1.432408
[LightGBM] [Info] Start training from score 1.424034
0.7762869028478306 0.6667255207317859

In [89]:
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
import numpy as np

test_pred = stack_model.predict(test_data)

rmse = np.sqrt(mean_squared_error(test_target, test_pred))
mae = mean_absolute_error(test_target, test_pred)
r2 = r2_score(test_target, test_pred)

print('rmse:', rmse, '| mae:', mae, '| r2:', r2)

rmse: 1.5025403610025505 | mae: 0.8976101096358102 | r2: 0.6667255207317859

In [90]:
feature.corr()

,hour,cluster,mapped_dong_code,weekday,month,holiday,temperature,humidity,precipitation,wind_speed
hour,1.000000e+00,NaN,9.778052e-14,-1.266365e-17,6.059907e-17,-2.543171e-17,1.217539e-01,-2.573734e-01,7.863327e-03,1.632480e-01
cluster,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mapped_dong_code,9.778052e-14,NaN,1.000000e+00,-3.336533e-13,2.816279e-11,2.748713e-12,4.836032e-11,2.631104e-11,3.695053e-12,2.086575e-12
weekday,-1.266365e-17,NaN,-3.336533e-13,1.000000e+00,9.509313e-03,-4.766507e-02,1.988102e-03,2.200142e-02,-5.666330e-03,2.711310e-03
month,6.059907e-17,NaN,2.816279e-11,9.509313e-03,1.000000e+00,-4.308035e-02,2.262259e-01,1.967700e-01,3.410106e-02,-9.889947e-02
holiday,-2.543171e-17,NaN,2.748713e-12,-4.766507e-02,-4.308035e-02,1.000000e+00,-4.080711e-02,6.363866e-04,1.594897e-02,1.571392e-02
temperature,1.217539e-01,NaN,4.836032e-11,1.988102e-03,2.262259e-01,-4.080711e-02,1.000000e+00,1.588475e-01,1.341622e-01,1.622995e-02
humidity,-2.573734e-01,NaN,2.631104e-11,2.200142e-02,1.967700e-01,6.363866e-04,1.588475e-01,1.000000e+00,1.729101e-01,-2.533578e-01
precipitation,7.863327e-03,NaN,3.695053e-12,-5.666330e-03,3.410106e-02,1.594897e-02,1.341622e-01,1.729101e-01,1.000000e+00,1.541047e-01
wind_speed,1.632480e-01,NaN,2.086575e-12,2.711310e-03,-9.889947e-02,1.571392e-02,1.622995e-02,-2.533578e-01,1.541047e-01,1.000000e+00

연속되지 않은 수치(cluster) feature에서 제외하여 다시 모델 돌려보기